name: layout-builder-test
recipe: drupal8
config:
  webroot: web
services:
  appserver:
    webroot: web
    xdebug: true
    config:
      php: .vscode/php.ini
tooling:
  drupalupdate:
    service: appserver
    cmd:
      - composer update drupal/core webflo/drupal-core-require-dev --with-dependencies
      - drush updatedb
      - drush cr
