<?php

/**
 * @file
 * Contains custom_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_blocks module.
    case 'help.page.custom_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for custom blocks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_blocks_theme() {
  return [
    'custom_blocks' => [
      'render element' => 'children',
    ],
  ];
}
